language: ruby
bundler_args: --without development
rvm:
  - 2.3
  - 2.4
  - 2.5
  - jruby-9.0.5.0
  - rbx
matrix:
  allow_failures:
    - rvm: rbx
    - rvm: jruby-9.0.5.0
branches:
  only:
    - master
sudo: false
